### ISSUE TITLE
Missing Heart Tanks in changed Mega Man X3 ROMs

### ISSUE THREAD

**Issue by sharivan** [rbrummett/megaedx_v1.3#1]
I noticed a possible bug when i modified a Mega Man X3 room using this version of MegaED X. After i changed some level design in most stages, when i tested the game, after i get one heart tank in any stage, i will be unnable to get the remaining because they will not appear anymore.

There is a simple example to reproduce this bug. Firstly, you will need to use my modified ROM where you can download at:

https://drive.google.com/open?id=1_QpXHuh1xTw2oWQz3fmcBF32qREB1qeA

To build this modified version of Mega Man X3, i used the original headerless USA version (MD5 cfe8c11f0dce19e4fa5f3fd75775e47c).

After you finish intro, you can enter at Tunnel Rhino stage and see the heart tank there (you will not able to get then of course) and then you defeat the boss and go to Blizzard Buffalo stage to get the heart tank in that stage using Tornado Fang. After you defeat the boss and go to another stage, you can return to Rhino stage just to see if the heart tank in that stage will still be there, and you will see no. Any stage you will visit, the heart tank of its stage will be missing.

I want to know if there is a soluction to fix it using MegaED X, if so, how? Otherwise, there is a way to i modify the ROM data to fix it without wait to a possible fix in MegaED X?

Thks in advance for any clarification;

**Comment by sharivan** [comment]
I forgot to mention it above, but this same bug occurs after you editing Mega Man X2 too, however, its not only hearts that fail to appear but also some capsules;

**Comment by Xeeynamo** [comment]
I received your comment's notification because I am watching this repo. But what puzzles me most is why do they literally copy&pasted my original MegaED X repository rather than forking it and working on top of it. For the sake of maintenance it is a mess and, even if I would like to fix your issue @sharivan , I would not have an idea of where to start lol.

I hope this will be solved as some point, with maybe a Pull Request on the original MegaED X or something...?

**Comment by rbrummett** [comment]
Hi. I'm not familiar with github too well. I have forked Xeeynamo's code, but I was working on Redguyy's source which included a bunch of new code, so I'm not able to do a pull request. I will look into uploading _my code_ to Xeeynamo's fork, so that a pull request can be made.

I have also gotten the rom from google drive and will look into the bug. Apologize for the late reply.

**Comment by sharivan** [comment]
No problem, thks for de answer and for the attention.

**Comment by rbrummett** [comment]
Hi, I was able to recreate this bug. Now I just need to find out why it's doing that. Did you move around the heart tanks at all? I got the heart tank in Toxic Seahorse stage and noticed you made a couple changes. Also, the ladders were very  short? Are they short because of a problem with the level editor or did you change the graphics? Thanks

**Comment by sharivan** [comment]
The only heart tank i changed was in Crawfish stage, the rest of them i didnt changed.

The ladders are very short on purpose, this hack was made with purpose to make the game difficult, forcing the player to use some speedrun techniques to get ahead in most of the game. In the case of stairs, the player will have to either use gap jumps (a speedrun technique to skip ladder climbs) or be equipped with boots and use upward dash.

**Comment by rbrummett** [comment]
@Sharivan, I was able to find out why it's not displaying the heart tank graphics, but I haven't figured out how to fix the bug yet. Basically, at @7e1fd4 in RAM it increments by 0x08 every time you collect a heart tank on Toxic Seahorse, but in your hack it only increments by 0x04. So even changing the value manually in RAM will fix the problem, but I need to do a trace route to find out why it's doing that. Probably some memory leaking between banks. Probably expanding the rom will fix. 

Can you upload a patch so I can see the same problem for X2? Thanks

**Comment by sharivan** [comment]
Hello, how long.

Here is the link to download my X2 hack:

https://drive.google.com/file/d/1eAMdhg2Q97BX4-zlMSAdgOJRoLpVbQqC

This hack was just a test for the level editor, i could see that for X2 the editor had a lot more problems, only on X3 i could have a better progress with the edits, although it's still not perfect.

Thks for your efforts.

**Comment by rbrummett** [comment]
Hi, thanks. I think I've narrowed down the issue. Should be resolved shortly.

**Comment by rbrummett** [comment]
I've fixed the bug, updated the source code, and added a directory for binaries where you can download the latest executable. I'm going to mark this issue as closed.

**Comment by sharivan** [comment]
Thks very much man, i will check and test it soon.
